### ISSUE TITLE
Métodos não estáticos

### ISSUE THREAD

**Issue by SilvaEngComp** [JoggApp/laravel-natural-language#11]
Olá tentei utilizar os métodos, como descrito na documentação, mas ao acessar a classe ví que os métodos da classe NaturalLanguage não são estáticos, como mostrado na documentação. Houve alguma mudança? Dentro da configuração atual teria que passar o id do projeto e as credenciais no instanciamento da classe NaturalLanguageClient.

Eu criei o projeto no google cloud, adicionei a api, criei a chave de serviço, configurei as variáveis de ambiente no .env e coloquei o caminho do arquivo no config/naturallanguage.php. Segui todos os passos especificados aqui:
https://github.com/JoggApp/laravel-natural-language/blob/master/google.md

TIve que instanciar um objeto para conseguir utilizar. Fica a susgestão uma mudança na documentação ou alterar os métodos para serem estáticos. Segue abaixo o código:

use JoggApp\NaturalLanguage\NaturalLanguage;
use JoggApp\NaturalLanguage\NaturalLanguageClient;
use Config;

class NlpController extends Controller
{

    private NaturalLanguage $naturalLanguage;

    public function __construct()
    {

        $this->naturalLanguage = new NaturalLanguage(new NaturalLanguageClient(config('naturallanguage')));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return $this->naturalLanguage->sentiment($request->input('text'));
    }
}

**Comment by SilvaEngComp** [comment]
Eu criei o projeto no google cloud, adicionei a api, criei a chave de serviço, configurei as variáveis de ambiente no .env e coloquei o caminho do arquivo no config/naturallanguage.php. Segui todos os passos especificados aqui: 
https://github.com/JoggApp/laravel-natural-language/blob/master/google.md

**Comment by introwit** [comment]
please post it in English
