### ISSUE TITLE
Doesn't install with Composer v2

### ISSUE THREAD

**Issue by jpcaparas** [JoggApp/laravel-natural-language#7]
Got this error when running `composer require joggapp/laravel-natural-language`:

```
In PackageManifest.php line 131:
                         
  Undefined index: name  
                         

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Had to revert to a deprecated Composer V1 to get it to work.

Running PHP 7.4

**Comment by introwit** [comment]
I just tried it with composer v2, and it is working fine. Could be some other package that's causing the problem at your end.
