### ISSUE TITLE
Putting in auth key file path in an .env directive 

### ISSUE THREAD

**Issue by jpcaparas** [JoggApp/laravel-natural-language#8]
Would it be better to have the file path stored as a directive?

On `naturallanguage.php`:

```
'key_file_path' => base_path(env('NATURAL_LANGUAGE_KEY_FILE_PATH')),
```

... and on `.env.example`:

```
NATURAL_LANGUAGE_KEY_FILE_PATH=nlp-auth.json
```

Just a thought.

**Comment by introwit** [comment]
it's the same thing, just delegated 1 step deeper.
